algoritmo "Par_Impar"
// Função :  Escreva um algoritmo que determine (imprima) se um dado número N
//inteiro é PAR ou ÍMPAR.
// Autor :   marilia silva https:maliarte.com.br
// Data : 13/08/2020
// Seção de Declarações
var
       num1: inteiro

inicio
escreval("Informe o numero: ")
leia(num1)
se (num1 mod 2 = 0) entao
escreval ("O numero",num1," é par!")
senao
escreval ("O numero",num1," é impar!")
fimse

fimalgoritmo
