algoritmo "Calcular o quadrado de um numero ou seja, o produto de um numero por ele mesmo"
// Funcao : Calcular o quadrado de um numero, ou seja, o produto de um número por si mesmo.
// Autor : Marilia Silva
// Data : 14/07/2020
// Secao de Declaracoes
var
      num: inteiro
      quadrado: real
inicio
// Secao de Comandos
Escreva("Informe o numero: ")
Leia(num)
quadrado:= num*num
Escreval("O Quadrado do numero ", num, " é: ", quadrado)


 
fimalgoritmo
