algoritmo "Selecao composta ou dupla"
// Funcao :  Escreva um algoritmo que leia um numero e imprima-o, caso ele seja maior
//que 20.

// Autor : Marilia Silva | https://maliarte.com.br
// Data : 15/07/2020

var
         num: inteiro
inicio
escreva("Informe um numero: ")
leia(num)
         Se(num>20)entao
              escreval("Esse número é maior que 20!")
         Senao
              escreval("Numero fora de escopo!")
         Fimse
fimalgoritmo
