algoritmo "Seleção_Composta"
// Função :  Escreva um algoritmo que leia um número e imprima-o, caso ele seja maior
//que 20.
// Autor :  Marilia Silva | https://maliarte.com.br
// Data : 13/08/2020

var
      num: inteiro
inicio

Escreval("Informe um numero: ")
leia(num)
         se num > 20 entao
         escreval("Numero maior que 20")
         senao
         escreval("tente outra vez")
         fimse
fimalgoritmo
